bobMinimumVersion: "1.1"
layers:
    - name: basement-gnu-linux
      scm: git
      url: https://github.com/BobBuildTool/basement-gnu-linux.git
      commit: c1d98bf23f1f86bf37220ff956dbccd5094f66b9
    - name: basement
      scm: git
      url: https://github.com/BobBuildTool/basement.git
      commit: b79927c309a08bfd6daed00385a88576bad5310d
